update=Mon Oct 22 22:27:17 2012
last_client=cvpcb
[pcbnew]
[pcbnew/libraries]
LibName1=sockets
LibName2=connect
LibName3=discret
LibName4=pin_array
LibName5=divers
LibName6=libcms
LibName7=display
LibName8=led
LibName9=dip_sockets
LibName10=pga_sockets
LibName11=valves
LibName12=bonefpga
LibDir=/home/mike/bonefpga/HardwareDesignFiles/lib
[cvpcb]
version=1
NetIExt=net
[cvpcb/libraries]
EquName1=devcms
